import clsx from "clsx";
import { Inter, Pacifico, Signika } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const pacifico = Pacifico({
	weight: ["400"],
	subsets: ["latin"],
	variable: "--font-pacifico",
});
const signika = Signika({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	display: "swap",
	style: ["normal"],
	variable: "--font-signika",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={clsx(
					inter.variable,
					pacifico.variable,
					signika.variable,
					"bg-isBlack font-sans"
				)}
			>
				{children}
			</body>
		</html>
	);
}
